name: operation
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^8.0.3
  flutter_bloc: ^9.0.0
  oktoast: ^3.4.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  logger: ^2.5.0
  firebase_core: ^3.10.0
  firebase_analytics: ^11.4.0
  firebase_crashlytics: ^4.3.0
  go_router: ^14.6.3
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.4
  intl: ^0.20.1
  shimmer: ^3.0.0
  iconsax: ^0.0.8
  flutter_svg: ^2.0.17
  webview_flutter: ^4.11.0
  calendar_date_picker2: ^1.1.9
  url_launcher: ^6.3.1
  http_parser: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  lint: ^2.3.0
  flutter_lints: ^5.0.0
  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.5
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1

dependency_overrides:
  intl: ^0.20.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
