name: Flutter Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.8"

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-builds
          path: build/app/outputs/flutter-apk/*.apk
          retention-days: 7

  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.32.8"

      - name: Install dependencies
        run: flutter pub get

      - name: Build IPA
        run: flutter build ipa --release --no-codesign

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ios-builds
          path: build/ios/ipa/*.ipa
          retention-days: 7
